// src/utils/industryMapping.js

export const industryNameToNumber = {
  "Agriculture": 1,
  "Food Products": 2,
  "Candy & Soda": 3,
  "Beer & Liquor": 4,
  "Tobacco Products": 5,
  "Recreation": 6,
  "Entertainment": 7,
  "Printing and Publishing": 8,
  "Consumer Goods": 9,
  "Apparel": 10,
  "Healthcare": 13,
  "Medical Equipment": 12,
  "Pharmaceutical Products": 14,
  "Chemicals": 15,
  "Rubber and Plastic Products": 16,
  "Textiles": 17,
  "Construction Materials": 18,
  "Construction": 19,
  "Steel Works Etc": 20,
  "Fabricated Products": 21,
  "Machinery": 22,
  "Electrical Equipment": 23,
  "Automobiles and Trucks": 24,
  "Aircraft": 25,
  "Shipbuilding, Railroad Equipment": 26,
  "Defense": 27,
  "Precious Metals": 28,
  "Non-Metallic and Industrial Metal Mining": 29,
  "Coal": 30,
  "Petroleum and Natural Gas": 31,
  "Utilities": 32,
  "Communication": 33,
  "Personal Services": 34,
  "Business Services": 35,
  "Computers": 36,
  "Electronic Equipment": 37,
  "Measuring and Control Equipment": 38,
  "Business Supplies": 39,
  "Shipping Containers": 40,
  "Transportation": 41,
  "Wholesale": 42,
  "Retail": 43,
  "Restaurants, Hotels, Motels": 44,
  "Banking": 45,
  "Insurance": 46,
  "Real Estate": 47,
  "Trading": 48,
  "Almost Nothing": 49
};
