export const industryNameToNumber = {
  "Agriculture": 1,
  "Food Products": 2,
  "Candy & Soda": 3,
  "Beer & Liquor": 4,
  "Tobacco Products": 5,
  "Recreation": 6,
  "Entertainment": 7,
  "Printing and Publishing": 8,
  "Consumer Goods": 9,
  "Apparel": 10,
  "Healthcare": 11,
  "Medical Equipment": 12,
  "Pharmaceutical Products": 13,
  "Chemicals": 14,
  "Rubber and Plastic Products": 15,
  "Textiles": 16,
  "Construction Materials": 17,
  "Construction": 18,
  "Steel Works Etc": 19,
  "Fabricated Products": 20,
  "Machinery": 21,
  "Electrical Equipment": 22,
  "Automobiles and Trucks": 23,
  "Aircraft": 24,
  "Shipbuilding, Railroad Equipment": 25,
  "Defense": 26,
  "Precious Metals": 27,
  "Non-Metallic and Industrial Metal Mining": 28,
  "Coal": 29,
  "Petroleum and Natural Gas": 30,
  "Utilities": 31,
  "Communication": 32,
  "Personal Services": 33,
  "Business Services": 34,
  "Computers": 35,
  "Electronic Equipment": 36,
  "Measuring and Control Equipment": 37,
  "Business Supplies": 38,
  "Shipping Containers": 39,
  "Transportation": 40,
  "Wholesale": 41,
  "Retail": 42,
  "Restaurants, Hotels, Motels": 43,
  "Banking": 44,
  "Insurance": 45,
  "Real Estate": 46,
  "Trading": 47,
  "Almost Nothing": 48
};
