CREATE TABLE tweets (
  coordinates INT,
  created_at TIMESTAMP,
  favorited BOOLEAN,
  truncated BOOLEAN,
  tweet_id_str TEXT ENCODING DICT(16),
  in_reply_to_user_id_str TEXT ENCODING DICT(8),
  tweet_text TEXT ENCODING DICT(16),
  tweet_contributors TEXT ENCODING DICT(8),
  id BIGINT,
  retweet_count INT,
  in_reply_to_status_id_str TEXT ENCODING DICT(8),
  geo TEXT ENCODING DICT(8),
  retweeted BOOLEAN,
  in_reply_to_user_id TEXT ENCODING DICT(8),
  user_profile_sidebar_border_color TEXT ENCODING DICT(8),
  user_name TEXT ENCODING DICT(8),
  user_profile_sidebar_fill_color TEXT ENCODING DICT(8),
  user_profile_background_tile BOOLEAN,
  user_profile_image_url TEXT ENCODING DICT(8),
  user_location TEXT ENCODING DICT(8),
  user_created_at TIMESTAMP,
  user_id_str TEXT ENCODING DICT(8),
  user_follow_request_sent BOOLEAN,
  user_profile_link_color TEXT ENCODING DICT(8),
  user_favourites_count INT,
  user_url TEXT ENCODING DICT(16),
  user_contributors BOOLEAN,
  user_utc_offset DOUBLE,
  user_id INT,
  user_profile_use_background_image TEXT ENCODING DICT(16),
  user_listed_count INT,
  user_protected BOOLEAN,
  user_lang TEXT ENCODING DICT(8),
  user_profile_text_color TEXT ENCODING DICT(8),
  user_followers_count INT,
  tweet_user_time_zone TEXT ENCODING DICT(8),
  user_verified BOOLEAN,
  user_geo_enabled BOOLEAN,
  user_profile_background_color TEXT ENCODING DICT(8),
  user_notifications BOOLEAN,
  user_description TEXT ENCODING DICT(16),
  user_friends_count INT,
  user_profile_background_image_url TEXT ENCODING DICT(16),
  user_statuses_count INT,
  user_screen_name TEXT ENCODING DICT(16),
  user_following INT,
  in_reply_to_screen_name TEXT ENCODING DICT(16),
  tweet_source TEXT ENCODING DICT(16),
  place TEXT ENCODING DICT(16),
  in_reply_to_status_id INT,
  favorite_count INT,
  screen_name TEXT ENCODING DICT(16),
  tweet_lang TEXT ENCODING DICT(8),
  screen_name2 TEXT ENCODING DICT(16),
  EST TIMESTAMP,
  screen_name3 TEXT ENCODING DICT(16),
  user_created_EST TIMESTAMP,
  tweetQuarter SMALLINT,
  tweetmonth SMALLINT,
  tweetyear SMALLINT,
  containLink BOOLEAN,
  numWords INT,
  numCharacters INT,
  screen_name4 TEXT ENCODING DICT(16),
  col_id BIGINT,
  tweet_text_adj TEXT ENCODING DICT(16)
);
